version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: vite_docker
    ports:
      - 3001:3001
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    networks:
      - kafka-network
      
networks:
  kafka-network:
    external: true
